## 📝 Practice Questions Set - 24 Questions


---


### 🧮 A. Array Properties

      - 1 Create a 2D NumPy array of shape (4, 3) filled with any numbers.    
        Print its .shape, .size, .ndim, and .dtype.
        
      - 2 Create a 3D array of shape (2, 2, 3).    
        Verify the number of dimensions and total elements using .ndim and .size.
        
      - 3 Create a 1D NumPy array with numbers from 10 to 20.    
        Print its shape, size, ndim, and dtype.
        
      - 4 Create a 2D array (3 rows × 4 columns) filled with zeros.
        
      - 5 Create a 3×3 array filled with the number 7.
        
      - 6 Generate an array of even numbers between 50 and 100 (inclusive).
        
      - 7 Create an identity matrix of size 5×5.

In [1]:
import numpy as np

In [4]:
#  1 Create a 2D NumPy array of shape (4, 3) filled with any numbers.    
# Print its .shape, .size, .ndim, and .dtype.

arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(arr_2d)
print(arr_2d.shape, arr_2d.size, arr_2d.ndim, arr_2d.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3) 12 2 int32


In [14]:
# 2 Create a 3D array of shape (2, 2, 3).    
#     Verify the number of dimensions and total elements using .ndim and .size.

arr_3d = np.array([
    [[1,2,3],[4,5,6]],
    [[4,5,6],[1,2,3]]
])
print(arr_3d)
print(arr_3d.ndim, arr_3d.size)


[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]
3 12


In [16]:
# 3 Create a 1D NumPy array with numbers from 10 to 20.    
#     Print its shape, size, ndim, and dtype.

arr_1d = np.arange(10,21,1)
print(arr_1d)
print(arr_1d.shape, arr_1d.size, arr_1d.ndim, arr_1d.dtype)


[10 11 12 13 14 15 16 17 18 19 20]
(11,) 11 1 int32


In [20]:
# 4 Create a 2D array (3 rows × 4 columns) filled with zeros.

arr_2d = np.zeros((3,4))
print(arr_2d)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
 # 5 Create a 3×3 array filled with the number 7.
filled_array = np.full((3,3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [26]:
 # 6 Generate even numbers between 50 and 100 (inclusive).
even_array = np.arange(50,101)
print(even_array)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [28]:
 # 7 Create an identity matrix of size 5×5.

identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### 🧩 B. Type Conversion
    - 1 Create an integer array and convert it to: float using .astype(float)
    string using .astype(str)
    Print the converted arrays and check their .dtype.

    - 2 Create an array of floating numbers [1.5, 2.3, 5.7, 9.9] and convert it to integers using .astype(int).

    - 3 Create a 1D array of size 8 with values from 1 to 8, then reshape it into a 2D array of shape (2, 4).
    
    - 4 Check the number of dimensions (ndim) for a scalar, a 1D array, and a 3D array.
        

In [33]:
# 1 Create an integer array and convert it to a float using .astype(float)
# string using .astype(str)
# Print the converted arrays and check their .dtype.

int_arr = np.array([1,2,3,4,5])
print(int_arr, int_arr.dtype)

float_arr = int_arr.astype(float)
print(float_arr.dtype)


str_arr = int_arr.astype(str)
print(str_arr.dtype)

[1 2 3 4 5] int32
float64
<U11


✅ So your results are:

int32 → original integer array

float64 → after .astype(float)

<U11 → after .astype(str)

<U11 means: Unicode string with a maximum length of 11 characters per element.

Example: 1 → '1', 2 → '2', etc.

NumPy automatically picks the string length big enough to hold the largest value.

In [38]:
# 2 Create an array of floating numbers [1.5, 2.3, 5.7, 9.9] and convert it to integers using .astype(int).
floating_numbers = np.array([1.5, 2.3, 5.7, 9.9])
str_conversion = floating_numbers.astype(int)
print(str_conversion)


[1 2 5 9]


In [42]:
# 3 Create a 1D array of size 8 with values from 1 to 8, then reshape it into a 2D array of shape (2, 4).

array_1d = np.arange(1,9)
print(array_1d)
reshapeArr = np.reshape(array_1d,(2, 4))
print(reshapeArr)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [44]:
# 4 Check the number of dimensions (ndim) for a scalar, a 1D array, and a 3D array.


# Scalar (just a single number, 0D array)
scalar = np.array(7) 

# 1D array (like a list)
arr_1d = np.array([1, 2, 3, 4, 5]) 

# 3D array (a cube of numbers)
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(scalar.ndim, arr_1d.ndim, arr_3d.ndim)

0 1 3


---

### ➕ C. Math Operations (No Loops)

  - Create two arrays of shape (2, 3) and:
      - Add them    
      - Subtract them
      - Multiply them
      - Divide them
  - Create an array from 1 to 10.
      - Square each element using ** 2.
      - Add 5 to each element using +.
  
  - Create two arrays:
      - a = [10, 20, 30, 40]
      - b = [1, 2, 3, 4]
    Perform addition, subtraction, multiplication, division, and exponentiation between them.

  -  Given array arr = np.array([5, 10, 15, 20]), add 10 to every element without using a loop.

  - Multiply a 3×3 matrix by 2 directly (no loops).


In [29]:
# Create two arrays of shape (2, 3) and:
# Add them
# Subtract them
# Multiply them
# Divide them


arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr1 + arr2)




[[11 22 33]
 [44 55 66]]


In [27]:
# Create an array from 1 to 10.

# Square each element using ** 2.
# Add 5 to each element using +.


array = np.arange(1,11)
print('Array Elements: ', array)
print('Square of Array: ', array ** 2)
print('Add 5 to Array: ', array + 5)

Array Elements:  [ 1  2  3  4  5  6  7  8  9 10]
Square of Array:  [  1   4   9  16  25  36  49  64  81 100]
Add 5 to Array:  [ 6  7  8  9 10 11 12 13 14 15]


In [35]:
# Create two arrays:

# a = [10, 20, 30, 40]
# b = [1, 2, 3, 4] Perform addition, subtraction, multiplication, division, and exponentiation between them. 

a = [10, 20, 30, 40]
b = [1, 2, 3, 4] 


a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(f'addition: {a+b} \nsubtraction: {a-b} \nmultiplication: {a*b} \ndivision: {a/b}')


addition: [11 22 33 44] 
subtraction: [ 9 18 27 36] 
multiplication: [ 10  40  90 160] 
division: [10. 10. 10. 10.]


In [49]:
# Given array arr = np.array([5, 10, 15, 20]), add 10 to every element without using a loop.
arr = np.array([5, 10, 15, 20])
print(f'Adding 10 to array = {arr} -> {arr + 10}')

Adding 10 to array = [ 5 10 15 20] -> [15 20 25 30]


In [53]:
# Multiply a 3×3 matrix by 2 directly (no loops).

matrix = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[1,2,3], [4,5,6], [7,8,9]],
    [[1,2,3], [4,5,6], [7,8,9]]
])

print(f'Multiply a 3×3 matrix by 2 directly \n{matrix * 2}')

Multiply a 3×3 matrix by 2 directly 
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


---
## 📊 D. Aggregation Functions

    Create a 2D array of random integers from 10 to 50 of shape (3, 4).
       - Find sum, mean, min, max, std, var.
    
    From the same array:
        Find the sum of each row (axis=1)
        Find the mean of each column (axis=0)

    Create a NumPy array of numbers from 1 to 25.
        Find its sum, mean, min, max, standard deviation, and variance.

    Given a 2D array:   
        arr = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])    
    
        Find the sum of all elements.
        Find the sum along rows (axis=1).        
        Find the sum along columns (axis=0).

In [22]:
# Create a 2D array of random integers from 10 to 50 of shape (3, 4).
#    - Find sum, mean, min, max, std, var.

# array_2d = np.arange(10,51)  #-- didn't able to generate randon digits

array_2d = np.random.randint(10,50,(3,4))
print(array_2d)

print(array_2d.ndim)

print(array_2d.sum(), array_2d.mean(), array_2d.min(), array_2d.max(), array_2d.std(), array_2d.var())


[[43 46 44 24]
 [41 26 43 33]
 [48 17 37 18]]
2
420 35.0 17 48 10.637982264821966 113.16666666666667


In [28]:
# 2 From the same array:
#     Find the sum of each row (axis=1)
#     Find the mean of each column (axis=0)


print(np.sum(array_2d, axis = 1))  #🔹 This adds numbers **across each row**
print(np.mean(array_2d, axis = 0)) #🔹 This calculates **average down each column**

[157 143 120]
[44.         29.66666667 41.33333333 25.        ]


In [32]:
# Create a NumPy array of numbers from 1 to 25.
#     Find its sum, mean, min, max, standard deviation, and variance.

NumPyArray = np.arange(1,25)
print(NumPyArray.sum(), NumPyArray.mean(), NumPyArray.min(), NumPyArray.std(), NumPyArray.var())


300 12.5 1 6.922186552431729 47.916666666666664


In [34]:
# Given a 2D array:
#     Find the sum of all elements.
#     Find the sum along rows (axis=1).        
#     Find the sum along columns (axis=0).

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])  
print('sum of all elements ', arr.sum())
print('sum along rows (axis=1)', np.sum(arr, axis=1))
print('sum along rows (axis=0)', np.sum(arr, axis=0))



sum of all elements  45
sum along rows (axis=1) [ 6 15 24]
sum along rows (axis=0) [12 15 18]




| Goal                  | Function              | Works with reshape?      |
| --------------------- | --------------------- | ------------------------ |
| Sequential values     | `np.arange()`         | ✅ yes                    |
| Random integer values | `np.random.randint()` | ✅ directly creates shape |
 
### 📌 `numpy.random.randint()` — Syntax

```python
numpy.random.randint(low, high=None, size=None, dtype=int)
```

---

### 📖 Parameters

| Parameter | Description                                                                     |
| --------- | ------------------------------------------------------------------------------- |
| `low`     | Lowest (inclusive) integer that can be drawn                                    |
| `high`    | Highest (exclusive) integer (optional). If not given, `0` to `low` will be used |
| `size`    | Shape (number of elements) of the output array — e.g. `(3, 4)`                  |
| `dtype`   | Data type of output (default is `int`)                                          |

---

### ⚡ Example

```python
import numpy as np

# random integers from 10 (inclusive) to 50 (exclusive), shape (3,4)
arr = np.random.randint(10, 51, size=(3, 4))
print(arr)
```

**Output (example):**

```
[[32 45 21 19]
 [50 11 40 23]
 [18 44 29 13]]
```

---


### 🧮 `axis` meaning

* **axis=0 → column-wise (downwards)**
* **axis=1 → row-wise (across)**

---

### 💡 1. Sum of each row → `axis=1`

```python
np.sum(arr, axis=1)
```

🔹 This adds numbers **across each row**
🔹 Output: 1D array with sum of each row

---

### 💡 2. Mean of each column → `axis=0`

```python
np.mean(arr, axis=0)
```

🔹 This calculates **average down each column**
🔹 Output: 1D array with mean of each column

--- 


---
## 🧠 E. Mixed Challenge

    Make a 1D array of values from 0 to 15.
    
        Reshape it into shape (3, 5)
        Convert to float        
        Multiply all elements by 10
        Find the maximum value and its index (np.argmax())

    Create a 1D array of numbers from 1 to 10, then square every element.

    Generate a 2D array (4×4) with values from 1 to 16. Extract:
        The first row    
        The last column    
        A 2×2 sub-matrix from the middle
    
    Create a 1D array of 10 random integers between 1 and 100.
        Find the maximum and minimum value.
        Find the index of the maximum and minimum value.

In [45]:
# Make a 1D array of values from 0 to 15.

#     Reshape it into shape (3, 5)
#     Convert to float        
#     Multiply all elements by 10
#     Find the maximum value and its index (np.argmax())

Array1D = np.arange(0,15)

print(Array1D)
print('Reshape into shape (3, 5) \n', np.reshape(Array1D, (3, 5)))
print('Convert to float \n', Array1D.astype(float))
print('Multiply all elements by 10  \n', Array1D * 10)
print('maximum value \n', Array1D.max())
print('index \n', np.argmax(Array1D))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshape into shape (3, 5) 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Convert to float 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
Multiply all elements by 10  
 [  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140]
maximum value 
 14
index 
 14




## 🧠 `np.argmax()` — Meaning

**`argmax()`** gives the **index (position)** of the **maximum value** in an array.
 

### 📌 Syntax

```python
np.argmax(array, axis=None)
```

* `axis=None` → gives the position in the **flattened (1D) array**
* `axis=0` → gives the index of the max value **in each column**
* `axis=1` → gives the index of the max value **in each row**
 


In [81]:
# Create a 1D array of numbers from 1 to 10, then square every element.

arr1 = np.arange(1,10)
print(arr1)
print('square every element', arr1 ** 2)

# Generate a 2D array (4×4) with values from 1 to 16. Extract:
#     The first row    
#     The last column    
#     A 2×2 sub-matrix from the middle

arr2d = np.arange(1,17).reshape(4,4)
print(arr2d)
print('The first row ', arr2d[0])
print('The last column ',arr2d[-1] )

subArray = arr2d[1:3, 1:3]
print('A 2×2 sub-matrix from the middle \n', subArray)

[1 2 3 4 5 6 7 8 9]
square every element [ 1  4  9 16 25 36 49 64 81]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The first row  [1 2 3 4]
The last column  [13 14 15 16]
A 2×2 sub-matrix from the middle 
 [[ 6  7]
 [10 11]]


✅ **Summary — 2×2 Sub-matrix in NumPy**
* Use slicing:

  ```python
  arr[start_row:start_row+2, start_col:start_col+2]
  ```

* **Rules:**

  * `start_row` → starting row index
  * `start_col` → starting column index
  * `end` index is **excluded**

* This selects a **2×2 block** from the given 2D array.



In [92]:
# Create a 1D array of 10 random integers between 1 and 100.
#     Find the maximum and minimum value.
#     Find the index of the maximum and minimum value.

randomInt = np.random.randint(1,100, 10)
print(randomInt)
print(f'maximum value: {randomInt.max()} and minimum value: {randomInt.min()}')
print(f'index of the maximum value: {np.argmax(randomInt)} and minimum value: {np.argmin(randomInt)}')

[43 77 35 95 27 55 27 63 22 54]
maximum value: 95 and minimum value: 22
index of the maximum value: 3 and minimum value: 8
