
## 🔹 Indexing

1. Create a 1D NumPy array from 10 to 19.

   * Get the element at index `3`.
   * Get the last element.

2. Create a 2D array of shape (3,4) with numbers from 1 to 12.

   * Extract the element at row 1, column 2.
   * Extract the entire second row.



In [5]:
import numpy as np

In [53]:
# Create a 1D NumPy array from 10 to 19.

# Get the element at index 3.
# Get the last element.

array1d = np.arange(10,20)
print('Question: Create a 1D NumPy array from 10 to 19.Q1,Q2 \n\t\t\t----------------')
print(array1d)
print(f'the element at index 3 in {array1d} is --> {array1d[3]}')
print(f'the last element of {array1d} is {array1d[-1]}')



# Create a 2D array of shape (3,4) with numbers from 1 to 12.

# Extract the element at row 1, column 2.
# Extract the entire second row.
# Extract the entire second column.

print('__________________________________________________________________________________________\n')
print('Question: Create a 2D array of shape (3,4) with numbers from 1 to 12 Followed by Q1,q2,a3  \n\t\t\t----------------')



array2d = np.arange(1,13).reshape(3,4)
print(array2d)
print(f'the element at row 1, column 2 -> \n {array2d[1,2]} ')
print(f'the entire second row {array2d[2:]}')

print(f'the entire second column {array2d[:, 2]}')



Question: Create a 1D NumPy array from 10 to 19.Q1,Q2 
			----------------
[10 11 12 13 14 15 16 17 18 19]
the element at index 3 in [10 11 12 13 14 15 16 17 18 19] is --> 13
the last element of [10 11 12 13 14 15 16 17 18 19] is 19
__________________________________________________________________________________________

Question: Create a 2D array of shape (3,4) with numbers from 1 to 12 Followed by Q1,q2,a3  
			----------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the element at row 1, column 2 -> 
 7 
the entire second row [[ 9 10 11 12]]
the entire second column [ 3  7 11]




---

## 🔹 Slicing

3. From the 1D array `[0,1,2,3,4,5,6,7,8,9]`,

   * Get numbers from index 2 to 6.
   * Get every 2nd element.
   * Reverse the array using slicing.

4. From the 2D array of shape (4,4) with values `0–15`:

   * Slice the first two rows and first three columns.
   * Slice the last row only.

In [77]:
# From the 1D array [0,1,2,3,4,5,6,7,8,9],

# Get numbers from index 2 to 6.
# Get every 2nd element.
# Reverse the array using slicing.

print('1.Get numbers from index 2 to 6. \t\t 2.Get every 2nd element. \t\t 3.Reverse the array using slicing.')
print('\t\t\t\t ----------')


array1d =  [0,1,2,3,4,5,6,7,8,9]
print(array1d)
print(f'numbers from index 2 to 6. {array1d[2:6]}')
print(f'Get every 2nd element. {array1d[::2]}')
print(f'Reverse the array using slicing.. {array1d[::-1]}')



# From the 2D array of shape (4,4) with values 0–15:

# Slice the first two rows and first three columns.
# Slice the last row only.

print('__________________________________________________________________________________________\n')

print('From the 2D array of shape (4,4) with values 0–15: \t\t 1. Slice the first two rows and first three columns. \t\t 3. Slice the last row only.')
print('\t\t\t\t ----------')

array2d = np.arange(0,16).reshape(4,4)
print(array2d)
print(f'\nSlice the first two rows\n {array2d[0:2]} \n\nand first three columns.\n {array2d[:, 0:3]}')
print(f'\n\nSlice the last row only: {array2d[-1:]}')

1.Get numbers from index 2 to 6. 		 2.Get every 2nd element. 		 3.Reverse the array using slicing.
				 ----------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
numbers from index 2 to 6. [2, 3, 4, 5]
Get every 2nd element. [0, 2, 4, 6, 8]
Reverse the array using slicing.. [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
__________________________________________________________________________________________

From the 2D array of shape (4,4) with values 0–15: 		 1. Slice the first two rows and first three columns. 		 3. Slice the last row only.
				 ----------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Slice the first two rows
 [[0 1 2 3]
 [4 5 6 7]] 

and first three columns.
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


Slice the last row only: [[12 13 14 15]]




---

## 🔹 Fancy Indexing

5. Given `arr = np.array([10,20,30,40,50])`:

   * Extract elements at positions `[0, 2, 4]`.

6. Create a 3x3 array with numbers 1–9.

   * Use fancy indexing to pick elements `(0,0)`, `(1,1)`, `(2,2)` (diagonal).

In [101]:
# Given arr = np.array([10,20,30,40,50]):

# Extract elements at positions [0, 2, 4].

arr = np.array([10,20,30,40,50])
print(arr)
print(f'Extract elements at positions [0, 2, 4] ---->\t{arr[[0, 2, 4]]}')

# Create a 3x3 array with numbers 1–9.
# Use fancy indexing to pick elements (0,0), (1,1), (2,2) (diagonal).

print('\n\n \t\t ------ \n\n')
array3d = np.arange(1,10).reshape(3,3)
print(array3d)
# print(f' Use fancy indexing to pick elements (0,0), (1,1), (2,2) (diagonal) ---> {array3d[[0, 1, 2], [0, 1, 2]]}')
print(f"Use fancy indexing to pick diagonal elements ---> {array3d[[0,1,2],[0,1,2]]}")

#   OR

print("using np.diag(array) ")

print(np.diag(array3d))


[10 20 30 40 50]
Extract elements at positions [0, 2, 4] ---->	[10 30 50]


 		 ------ 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Use fancy indexing to pick diagonal elements ---> [1 5 9]
using np.diag(array) 
[1 5 9]




---

## 🔹 Boolean Masking

7. From `arr = np.array([5,10,15,20,25,30])`:

   * Extract values greater than 15.
   * Extract even numbers only.

8. From a 3x3 matrix of values 1–9,

   * Get all elements greater than 5.


In [109]:
arr = np.array([5,10,15,20,25,30])
print(arr)
print(f'extract values greater than 15. \t {arr[arr>15]}')
print(f'Extract even numbers only. \t {arr[arr%2 == 0]}')

print('\n\n\t\t\t ----- \n\n')
arr3d = np.arange(1,10).reshape(3,3)
print(f'{arr3d}.\n Get all elements greater than 5.\n {arr3d[arr3d>5]}')

[ 5 10 15 20 25 30]
extract values greater than 15. 	 [20 25 30]
Extract even numbers only. 	 [10 20 30]


			 ----- 


[[1 2 3]
 [4 5 6]
 [7 8 9]].
 Get all elements greater than 5.
 [6 7 8 9]



---

## 🔹 Array Shape

9. Create a 1D array with 12 elements.

   * Find its `.shape`.
   * Reshape it into (3,4).

10. Given `arr = np.arange(24)`,

* Reshape into (2,3,4).
* What is the total number of elements?

In [115]:

array1d = np.arange(1,13)
print(array1d)
print(array1d.shape)

reshaping = array1d.reshape(3,4)
print(reshaping)

print('\n\n\t\t ----- \n\n')

arr = np.arange(24)
print(arr)
reshaping = arr.reshape(2,3,4)
print(reshaping)
print(reshaping.shape)
print('total number of elements: ', arr.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


		 ----- 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
total number of elements:  24



---

## 🔹 Reshaping

12. Create a 1D array of 16 elements.

* Reshape it into (4,4).
* Reshape the same array into (2,2,4).
* Why must the product of dimensions remain the same?
    *   Answer : The product of dimensions must remain the same because reshaping does not create or remove elements, it only changes their arrangement. The total number of elements before and after reshape must be equal.


In [131]:
array1d = np.arange(0,16)
print(array1d)

print(f'Reshape it into (4,4).\n {array1d.reshape(4,4)}')
print(f'Reshape the same array into (2,2,4). \n{array1d.reshape(2,2,4)} ') 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshape it into (4,4).
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Reshape the same array into (2,2,4). 
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 





---

## 🔹 Ravel vs Flatten

11. Create a 2D array (3x3).

* Convert it into 1D using `.ravel()`.
* Modify one element in the ravelled array. Does it change the original?
* Repeat the same with `.flatten()` and check if original changes.


In [145]:
arr2d = np.arange(5, 14).reshape(3, 3)
print(arr2d)

c1d = arr2d.ravel()
print(c1d)
c1d[2] = 17 
print(arr2d)  

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[ 5  6  7  8  9 10 11 12 13]
[[ 5  6 17]
 [ 8  9 10]
 [11 12 13]]
[ 5  6 17  8  9 10 11 12 13]


In [147]:
arr2d = np.arange(5, 14).reshape(3, 3)
print(arr2d)

c1d = arr2d.flatten()
print(c1d)
c1d[0] = 15
print(arr2d)
print(c1d)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[ 5  6  7  8  9 10 11 12 13]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[15  6  7  8  9 10 11 12 13]



---

🔥 Bonus Challenge:
13\. Given `arr = np.arange(1,28)`,

* Reshape into (3,3,3).
* Extract the middle “slice” (the 2nd cube).
* Flatten it back to 1D.


In [179]:
arr = np.arange(1,28)
reshapeArr =  arr.reshape(3,3,3)
print(arr)

print(f'Reshape into (3,3,3). \n{reshapeArr}')
middle_cube = reshapeArr[1]

print()
print(f' Extract the middle “slice” (the 2nd cube). \n{middle_cube}')
print(f'Flatten it back to 1D.\n{reshapeArr.flatten()}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Reshape into (3,3,3). 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

 Extract the middle “slice” (the 2nd cube). 
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Flatten it back to 1D.
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
